### ISSUE TITLE
String format issue in log statement

### ISSUE THREAD

**Issue by chadmyers** [henriquecampos/NHibernate.Caches.Elasticache#5]
In [ElasticacheClient.cs line 124](https://github.com/henriquecampos/NHibernate.Caches.Elasticache/blob/master/NHibernate.Caches.Elasticache/ElasticacheClient.cs#L124) , the warning log has an invalid string format which causes the log4net log entry to fail.  log4net logs this to its own internal log:
```
<log4net.Error>Exception during StringFormat: Index (zero based) must be greater than or equal to zero and less than the size of the argument list. <format>could not save: {0} => {1} ({2})</format><args>{(entity description here), NHibernate.Cache.Entry.CacheEntry}</args></log4net.Error>
```

We should either remove the `({2})` or add in whatever the third value was supposed to be (_expiry)?

I'll be working up a pull request for this and submitting shortly.

**Comment by henriquecampos** [comment]
Thanks for your help
